version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=127.0.0.1
      - DB_NAME=scraped_news_articles
    volumes:
      - ./NewsArticleMiner:/app
    command: python3 pipeline.py

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=127.0.0.1
      - DB_NAME=scraped_news_articles
      - PORT=3000
      - LOG_FILE=scraping.log
    ports:
      - "3000:3000"
    volumes:
      - ./NewsArticleMiner/backend:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: scraped_news_articles
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
